apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::995094897584:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-F38VKDDS8BW1
      username: system:node:{{EC2PrivateDNSName}}
    - groups:       
      - system:masters       
      rolearn: arn:aws:iam::995094897584:role/UdacityFlaskDeployCBKubectlRole       
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-29T11:29:25Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:mapUsers: {}
    manager: eksctl.exe
    operation: Update
    time: "2020-11-29T11:29:25Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        f:mapRoles: {}
    manager: kubectl-edit
    operation: Update
    time: "2020-11-29T17:17:58Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "65884"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 8e235958-1db3-415b-b68f-650ddfd050eb
